import {Selector ,t} from 'testcafe'
class YourDetailsPage{
    constructor(){
        this.acceptCookies=Selector('#_evidon-banner-acceptbutton')
        this.houseNum= Selector('#HouseNumberOrName')
        this.postcode= Selector('#Postcode')
        this.findAdress=Selector('#find-address-button > a > span')
        this.homeOwner=Selector('#PropertyDetailsViewModel_HomePolicyholderIsHomeownerId_1')
        this.coverName=Selector('#PropertyDetailsViewModel_SelectedPackage_9')
        this.propertyType=Selector('#PropertyDetailsViewModel_PropertyTypeId')
        this.propertyTypeOption=this.propertyType.find('option')
        this.noOfBedroom=Selector('#PropertyDetailsViewModel_PropertyNumberOfBedroomsPostHomeTradingPilotId_3')
        this.noOfBathroom=Selector('#PropertyDetailsViewModel_PropertyNumberOfBathroomsId_2')
        this.noOfOtherroom=Selector('#PropertyDetailsViewModel_PropertyNumberOfOtherRoomsId_2')
        this.buildDate=Selector('#PropertyDetailsViewModel_PropertyConstructionYearId')
        this.buildDateOption=this.buildDate.find('option')
        this.buildyear=Selector('#PropertyDetailsViewModel_IndividualYearBuilt')
        this.buildyearOption=this.buildyear.find('option')
        this.wallMaterial=Selector('#PropertyDetailsViewModel_PropertyBuildingMaterialPostHomeTradingPilotId')
        this.wallMaterialOption=this.wallMaterial.find('option')
        this.roofMaterial=Selector('#PropertyDetailsViewModel_PropertyRoofMaterialPostHomeTradingPilotId')
        this.roofMaterialOption=this.roofMaterial.find('option')
        this.roofFlat=Selector('#PropertyDetailsViewModel_PropertyFlatRoofPercentageId')
        this.roofFlatOption=this.roofFlat.find('option')
        this.hasFlooded=Selector('#PropertyDetailsViewModel_PropertyHasBeenFloodedId_0')
        this.hadLandslip=Selector('#PropertyDetailsViewModel_PropertyHasHadSubsidenceId_0')
        this.listedBuilding=Selector('#PropertyDetailsViewModel_IsListedBuilding_0')
        this.noOfadult=Selector('#PropertyDetailsViewModel_NumberOfAdultsId_2')
        this.noOfchildren=Selector('#PropertyDetailsViewModel_NumberOfDependantsId_0')
        this.whenHomeUsed=Selector('#PropertyDetailsViewModel_PropertyUsageFrequencyId') 
        this.whenHomeUsedOption=this.whenHomeUsed.find('option')
        this.businessUse=Selector('#PropertyDetailsViewModel_PropertyBusinessUseId') 
        this.businessUseOption=this.businessUse.find('option') 
        this.hasSpecifiedItems=Selector('#SpecifiedItemsViewModel_HasSpecifiedItems_0')
        this.hasPossessionCovered=Selector('#PersonalPossessionsViewModel_IsPPCoverSelected_0')
        this.hasBicycle=Selector('#SpecifiedItemsViewModel_HasBicycles_0')
        this.hasInsurance=Selector('#ClaimsViewModel_HasClaims_0')
        this.buildingInsurance=Selector('#PolicyholderDetailsViewModel_NumberOfYearsBuildingInsuranceId')
        this.buildingInsuranceOption=this.buildingInsurance.find('option') 
        this.contentInsurance=Selector('#PolicyholderDetailsViewModel_NumberOfYearsContentsInsuranceId')
        this.contentInsuranceOption=this.contentInsurance.find('option') 
        this.title=Selector('#PolicyholderDetailsViewModel_PolicyholderTitle_1')
        this.firstName=Selector('#PolicyholderDetailsViewModel_PolicyholderFirstName')
        this.surName=Selector('#PolicyholderDetailsViewModel_PolicyholderSurname')
        this.birthDay= Selector('#PolicyholderDateOfBirthDay')
        this.birthMonth=Selector('#PolicyholderDateOfBirthMonth')
        this.birthYear=Selector('#PolicyholderDateOfBirthYear')
        this.empStatus=Selector('#PolicyholderDetailsViewModel_EmploymentStatus')
        this.empStatusOption=this.empStatus.find('option')
        this.isAddJointPolicyHolder=Selector('#JointPolicyholderViewModel_IsAddJointPolicyholderId_0')
        this.isAddInterestedParty=Selector('#InterestedPartyViewModel_IsThirdPartyInterestNoted_0')
        this.email=Selector('#PolicyholderDetailsViewModel_PolicyholderEmail')
        this.installment=Selector('#PolicyholderDetailsViewModel_IsDDMonthlyPaymentPreferred_1')
        this.submitBtn=Selector('#submit-your-details')
        this.autoOccupation=Selector('#auto-Occupation')
        this.autobusiness=Selector('#auto-Business')
    }
}
    export default YourDetailsPage